# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Magnamm Studio
email: maggotgluon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://magnamm.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

include:
  - "_pages"
exclude:
  - "/assets/"
  - "/bower_components/"
  - "bower.json"
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
